services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/leadflow
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=leadflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: